#!/bin/bash
# generated by http://www-app2.igb.illinois.edu/tools/qsub/
# ----------------QSUB Parameters----------------- #
#PBS -S /bin/bash
# \ PBS -q blacklight
# \ PBS -l nodes=1:ppn=1,mem=1000000mb
#PBS -M dlebauer@gmail.com
#PBS -m abe
#PBS -N rename-isimip
#PBS -d /home/groups/ebimodeling/met/isimip/

# ----------------Load Modules-------------------- #
module load nco/4.4.8

# ----------------Your Commands------------------- #

for ncfile in *.nc
do    
#    ncrename -d lat,latitude -d lon,longitude -v lat,latitude -v lon,longitude $ncfile global_$ncfile
    ncks -O -d longitude,-91.6,-87.4 -d latitude,37.0,42.75 $ncfile illinois$ncfile
done


