#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esg.pik-potsdam.de - 2014/05/08 20:16:45
# Search URL: http://esg.pik-potsdam.de/esg-search/wget/?query=*&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.prAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.prsnAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.psAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.rldsAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.rsdsAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.tasAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.tasmaxAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.tasminAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.uasAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.vasAdjust.v20130913|esg.pik-potsdam.de
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=https://esg.pik-potsdam.de/esgf-idp/openid/dlebauer
search_url='http://esg.pik-potsdam.de/esg-search/wget/?query=*&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.prAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.prsnAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.psAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.rldsAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.rsdsAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.tasAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.tasmaxAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.tasminAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.uasAdjust.v20130913|esg.pik-potsdam.de&dataset_id=isimip-ft.input.gfdl-esm2m.rcp85.day.vasAdjust.v20130913|esg.pik-potsdam.de'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' '8e9c1a0ac4a37f975ecc06eb997dab97'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' '063a53122eec2ed3ea4370b555874d0d'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' '48d905f6f66d6e436f0a65bbe538a659'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' '08bf014d4e460df5c1430535c7264008'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' 'de31d5e550a13893a0eeaf78533deb29'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' '1176358bf91f28c2c459fcf971bcf29e'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '6ca86e7748a6c6fdaba4cd919ada97a2'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' '506a550fcad0b55a7efb0b487b927c18'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' '8662aca10e4ddc0197ebabbda8b1c4bc'
'pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prAdjust/pr_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' '11df7265a1bd62a79a19c926be005432'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' 'f9ad12fba2b1b4b334424e90b6f9ae9d'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' '4e8d75166b6a2c2a8fb9fa65400fbe6c'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' '3a05a9a437b797dd4249fd2d1395fbe1'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' '9339b29b45893ed0e728f6589f939ec1'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' 'b7d6170c21a74a574ebb03ec0e308837'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' 'b424668f80ba32b43fc61dca73ed1e68'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '7d2071abd747cd7bdd92e06578f58d19'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' 'cb988fa9a0938f6f7da4078c57b19c9b'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' '4a911a0162ac2b06eb33d9ad43603fc8'
'prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/prsnAdjust/prsn_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' '24c3922465914ec7dd8227e55fcdf575'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' '1b1267730dc62d8c1dd02424d0b07cf4'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' 'f602a96844e85343db122dbebe4f2a47'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' '831922f812111d0e0be6101de58caada'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' '5136d5fc17029e8679cbbd025b2f2343'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' '40d0c30fb11f25662b82b36a51dceed3'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' '8945e63bfb04d19141e3cfc0f0349579'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '757e0c34722ab2f7150844f58a64c51a'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' '23321b77edef9e2bf5cf4f17c3edaba9'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' 'd8bcd4678911f4f550843488d9090ee7'
'ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/psAdjust/ps_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' 'de722a6062387a054150b23a7c8fd85d'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' '0049e88194ecc66251e79c489875d9f1'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' '44beff941ca27d6ee2f0b653c6f98665'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' 'ee3714a7287f7f1b71fd13f8b90e1798'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' 'a60a7e0c85053d628fb3a5466db4d6b4'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' '0008f5360de366b06f1e6ab15ac26a9a'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' '683d94ffa7c1fca8c6a1f62ed680cf52'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '6c84a5e1f7793d1e25362ca4fcc57389'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' 'd039f277616c02c61c54bd4912120054'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' 'db46a9b94d538aad9cefd5da53eabf80'
'rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rldsAdjust/rlds_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' '44d2a8c77ee71e85cc33f3eba48ae572'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' '5eef659b696c8ece8e5fd23ed571c98c'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' 'd22d77f0c929fc235a0739bffcf9843a'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' '8dd7d7f65055fe815d8942770adae8a3'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' 'cbcd602e9b1b73f9e9a2c694203ad969'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' '79261e5ff14a02bfc9b5551b07cd3cf2'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' 'fe2fe5e27ca6ddb56f3467fc72035aea'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' 'bd2f3a7c3937266856df23928f196be0'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' '0b20e8b388248a491b737da5717acfdd'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' 'df0e3306fd837770031722733685ab2a'
'rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/rsdsAdjust/rsds_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' 'd35e6127e955243fbdb12bf1911ea9a3'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' '2bbd833fdd1e727e9eb23e6fe42512cb'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' '9f2970edc3d0e84b1f526c94e6367261'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' '268c4d7f021a71df31eed26b541a9d60'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' 'f908b8f5746467c18e8b3ea5baca3f90'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' '0dbce17c82a4613e0367003331e49255'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' 'ad3aa4a4e56d9d2831c88e0cbf9c521d'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '4a0f9b468a92c4d9fe098fcabfc1f74f'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' '5ee0176f6ee62fc72cc7acc6e2b33f25'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' '78b57ac89ebe23d1d438513c36dd8ef9'
'tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasAdjust/tas_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' '17daada5fb807d5ea3ba1f4a9ab4c53b'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' '1caf19ff868499f2c25dd3d2bb8faa0b'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' '3cd3da7c7ba969316cc376d92fd26f67'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' 'e0fc55e88de15de5e45942f3dc58ab03'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' '95683b6de9248ebcaee9efb4e2cc73c9'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' '4a4b2644ea478d86066101e28e28fc1d'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' '73e7dabeaaf537221086e79548c6cb90'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '5a887e5e95b419f6fa8d934fa68b6ae8'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' '9331f2872909cc06fd8c39a914e6bc23'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' '614e23f3fa7e932f09fb5258773fa4a0'
'tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasmaxAdjust/tasmax_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' '1729b2257aecf3c37f5a63ce1f8d87cc'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' 'fb7d2faeb246e4961ae8e45981ab673c'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' '2fcab144439f43422e58ff3456c64ce7'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' 'd9bc79e8ade4b0882b919664c65cc66e'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' '39ea60154b11ae4b981a10541adb3456'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' 'f977d2ed1680322789a2cd5b5e06ac66'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' 'cd5d6e1947d9f880c2119b92be9e1810'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '6691fe0fcd4b04334b42cbf4c8fb6f03'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' '8449c3180b895022448670d37420dae9'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' '851bfed632b1bf2f9a0fa1d9b9376193'
'tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/tasminAdjust/tasmin_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' '2e987946899cf753534db0105c318407'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' 'c52d68aafb5393719539d166399c8605'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' '662779380d1dea296a84f31f457fe4b0'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' 'efeb1a2a6e8032ca3c9cf69abd0c4ea6'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' '38dbd2cccb4286187b54d9d4e170d7b8'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' '30cbaf10985b56e3d7cba09ddf5cff8a'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' 'cf7ee367724f52e3a07f8ef34a0382b7'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '47c86bbc8a660def271f5aeba2738563'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' '0c89ff4da3a3f268b7ea99867e300771'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' '445d53555218b99fde7aac7a0e3ee81a'
'uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/uasAdjust/uas_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' '0b17108a3ec580f541ba724fcc3d51c4'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2091-2099.nc' 'MD5' '8b4eca1c56af15356954ad7ffd7a1a3a'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2081-2090.nc' 'MD5' 'e6e83b5f443cdad86ab17d4953b5b851'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2071-2080.nc' 'MD5' 'ff266ca95a8f459831cb21ba69d9b4fa'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2061-2070.nc' 'MD5' '2f77f8473f4b071befc3b638bccda9f9'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2051-2060.nc' 'MD5' '6bb8a12de3b579bf6f4a9ea9b4398fdd'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2041-2050.nc' 'MD5' 'a0dbedbd7cbf4c488f2bef7ba1b5ad2f'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2031-2040.nc' 'MD5' '998a35b056f3bdd18d343428b03e6c49'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2021-2030.nc' 'MD5' 'c73c8a9ebf330262a4047094c7f94fd5'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2011-2020.nc' 'MD5' '71b0703572ea68310b68adc0322a376a'
'vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'http://esg.pik-potsdam.de/thredds/fileServer/isimip_dataroot/isimip-ft/input/gfdl-esm2m/rcp8p5/daily/vasAdjust/vas_bced_1960_1999_gfdl-esm2m_rcp8p5_2006-2010.nc' 'MD5' 'ef25cc349ea574cd6ba0a18e86737b8e'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
TRUSTSTORE=$ESG_HOME/esg-truststore.ts
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqh' OPT; do
    case $OPT in
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        p) clean_work=0;;               #       : preserve data that failed checksum
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day)
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1;;            #       : completely skip security. It will only work if the accessd data is not secured at all.
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java is required for retrieving the certificate and couldn't be found."
        exit 1
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if ((mVer<5)); then
        echo "Java version 1.5+ is required for retrieving the certificate." >&2
        echo "Current version seems older: $(java -version | head -n1) " >&2  
        exit 1
    fi
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from rainbow
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2
    
    if ! wget https://rainbow.llnl.gov/dist/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget https://rainbow.llnl.gov/dist/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

#get truststore from rainbow
get_truststore() {
    # don't if this was already done today
    [[ -z $force && "$(find $TRUSTSTORE -type f -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Truststore..." >&2
    
    if ! wget https://rainbow.llnl.gov/dist/certs/esg-truststore.ts -O $TRUSTSTORE -q ; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget https://rainbow.llnl.gov/dist/certs/esg-truststore.ts -O $TRUSTSTORE
        echo "Could't update truststore!" >&2
        return 1
    else
        touch $TRUSTSTORE
    fi
    
    echo "done!" >&2    
}

# Retrieve ESG credentials
unset pass
get_credentials() {
    check_java
    #get all certificates
    get_certificates
    #get truststore 
    get_truststore
    
    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q https://rainbow.llnl.gov/dist/devel/esgf-getcert/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    
    #get password
    pass=
    [[ ! "$pass" ]] && read -sp "MyProxy Password? " pass


    local args=
    [[ "$openId" ]] && args=$args" --oid $openId"
    [[ "$pass" ]] && args=$args" -P $pass"
    [[ "$username" ]] && args=$args" -l $username"
    
    echo -n $'\nRetrieving Credentials...' >&2
    if ! java $(proxy_to_java) -Djavax.net.ssl.trustStore=$TRUSTSTORE -Djavax.net.ssl.trustStorePassword=changeit -jar $MYPROXY_GETCERT $args --output $ESG_CREDENTIALS ; then        
        echo "Certificate could not be retrieved"
        exit 1
    fi
    echo "done!" >&2
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

get_mod_time_() {
    if ((LINUX)); then
        #on linux modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    elif ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                $wget -O "$file" $url || { failed=1; break; }
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

#
# MAIN
#
echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 100 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials
#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_
echo "done"
